
version: 2

models:
  - name: heures
    columns:
      - name: destination
        meta:
          dimension:
            label: "Destination"
      - name: type_train
      - name: arrival
      - name: arrival_base
      - name: departure
      - name: departure_base
      - name: delay


